name: Create shots.yml on first run

on: [push]

jobs:
  init:
    if: ${{ github.repository != 'simonw/shot-scraper-template' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            if (!fs.existsSync('shots.yml')) {
                const desc = context.payload.repository.description;
                let line = '';
                if (desc && (desc.startsWith('http://') || desc.startsWith('https://'))) {
                    line = `- url: ${desc}`;
                } else {
                    line = '# - url: https://www.example.com/';
                }
                fs.writeFileSync('shots.yml', line + '\n');
            }
            // And delete this workflow
            fs.unlinkSync('.github/workflows/setup.yml');
      - name: Force push new repo contents
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "shot-scraper with shots.yml"
